# Game settings
game:
  fps: 60
  move_interval: 123
  cell_size: 30
  grid_width: 16
  grid_height: 16
  best_score: 0

# Menu settings
menu:
  cell_size_values: [8, 16, 32, 48, 64]
  grid_size_values: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
